De Numpy a Pytorch

In [0]:
# importar numpy
import numpy as np

In [0]:
# importar pytorch
import torch

In [0]:
array1 = np.array([[1,2], [3, 4]])

In [0]:
print(array1)

[[1 2]
 [3 4]]


In [0]:
torch.Tensor(array1)

tensor([[1., 2.],
        [3., 4.]])

In [0]:
tensor1 = torch.ones(5)

In [0]:
print(tensor1)

tensor([1., 1., 1., 1., 1.])


In [0]:
array2 = tensor1.numpy()

In [0]:
print(array2)

[1. 1. 1. 1. 1.]


Hola Pytorch

In [0]:
# importado pytorch -> import torch

In [0]:
a = torch.empty(5,7, dtype=torch.float)

In [0]:
print(a)

tensor([[1.6425e-36, 0.0000e+00, 1.2472e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00,
         0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 7.0295e+28, 6.1949e-04, 2.3328e-18,
         6.9776e+22],
        [6.1972e-04, 7.2443e+22, 7.7052e+31, 1.6533e+19, 7.7140e+31, 3.3806e-18,
         1.0900e+27],
        [2.3364e-18, 4.5447e+30, 3.0750e+29, 1.9284e+31, 1.8891e+31, 2.0871e+37,
         1.0887e+27],
        [1.7830e+19, 1.7262e+25, 2.1975e+23, 7.1846e+22, 1.7516e-43, 0.0000e+00,
         0.0000e+00]])


In [0]:
print(a.size())

torch.Size([5, 7])


In [0]:
x = torch.randn((1,2))
y = torch.randn((1,3))

In [0]:
print(x)

tensor([[1.6190, 1.2513]])


In [0]:
print(y)

tensor([[-0.9264,  1.5442, -0.1429]])


In [0]:
matriz = torch.randn(3,3)

In [0]:
print(matriz)

tensor([[-0.6951, -1.3311,  1.5204],
        [ 0.9321, -0.3632,  0.1887],
        [-1.1635, -1.6849, -0.3452]])


In [0]:
print(torch.cuda.is_available())

True
